//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMAppServer
{
    using MMAppServer.Interfaces;
    using System;
    using System.Collections.Generic;
    
    public partial class Activity : IActivity
    {
        public long Id { get; set; }
        public long EntityId { get; set; }
        public int ActiveFrom { get; set; }
        public Nullable<int> ActiveTo { get; set; }
    
        public virtual Entity Entity { get; set; }
    }
}
